services:
  bollettinometeotrento.api:
    image: bollettinometeotrento.api
    build:
      context: .
      dockerfile: BollettinoMeteoTrento.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
